"""add contexto to ejecucion

Revision ID: 0c079acd217f
Revises: add_paso_assert
Create Date: 2026-05-12 13:40:32.713224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c079acd217f'
down_revision: Union[str, Sequence[str], None] = 'add_paso_assert'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_version_api_id'), table_name='api_version')
    op.drop_index(op.f('ix_api_version_id'), table_name='api_version')
    op.drop_table('api_version')
    op.add_column('ejecucion', sa.Column('contexto', sa.JSON(), nullable=False))
    op.drop_index(op.f('ix_paso_api_id'), table_name='paso')
    op.drop_constraint(op.f('paso_api_id_fkey'), 'paso', type_='foreignkey')
    op.drop_column('paso', 'api_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paso', sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('paso_api_id_fkey'), 'paso', 'api', ['api_id'], ['id'])
    op.create_index(op.f('ix_paso_api_id'), 'paso', ['api_id'], unique=False)
    op.drop_column('ejecucion', 'contexto')
    op.create_table('api_version',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('auth_tipo', sa.VARCHAR(length=20), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False),
    sa.Column('auth_config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('headers_por_defecto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_ejemplo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timeout_segundos', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('retries', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('creado_por_usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], name=op.f('api_version_api_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuario.id'], name=op.f('api_version_creado_por_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('api_version_pkey'))
    )
    op.create_index(op.f('ix_api_version_id'), 'api_version', ['id'], unique=False)
    op.create_index(op.f('ix_api_version_api_id'), 'api_version', ['api_id'], unique=False)
    # ### end Alembic commands ###
