"""Update  tabla caso_prueba

Revision ID: 71afbb460902
Revises: dda5977de82a
Create Date: 2026-05-14 14:02:41.326973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71afbb460902'
down_revision: Union[str, Sequence[str], None] = 'dda5977de82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caso_prueba', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('caso_prueba', sa.Column('precondiciones', sa.Text(), nullable=True))
    op.add_column('caso_prueba', sa.Column('postcondiciones', sa.Text(), nullable=True))
    op.add_column('caso_prueba', sa.Column('estado', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caso_prueba', 'estado')
    op.drop_column('caso_prueba', 'postcondiciones')
    op.drop_column('caso_prueba', 'precondiciones')
    op.drop_column('caso_prueba', 'descripcion')
    # ### end Alembic commands ###
