"""update models: proyecto, modulo, caso, paso, ejecucion

Revision ID: 96a7a6174411
Revises: 71afbb460902
Create Date: 2026-05-15 12:43:13.469743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a7a6174411'
down_revision: Union[str, Sequence[str], None] = '71afbb460902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejecucion', sa.Column('duracion_ms', sa.Integer(), nullable=True))
    op.add_column('ejecucion', sa.Column('caso_version', sa.Integer(), nullable=False))
    op.add_column('ejecucion', sa.Column('caso_nombre', sa.String(length=200), nullable=False))
    op.add_column('ejecucion', sa.Column('caso_objetivo', sa.Text(), nullable=True))
    op.add_column('ejecucion', sa.Column('caso_precondiciones', sa.Text(), nullable=True))
    op.add_column('ejecucion', sa.Column('caso_postcondiciones', sa.Text(), nullable=True))
    op.alter_column('ejecucion', 'resultado_global',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('modulo', sa.Column('estado', sa.String(length=50), nullable=False))
    op.add_column('modulo', sa.Column('responsable_id', sa.Integer(), nullable=True))
    op.add_column('modulo', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('modulo', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'modulo', 'usuario', ['responsable_id'], ['id'])
    op.add_column('paso', sa.Column('nombre', sa.String(length=200), nullable=False))
    op.add_column('paso', sa.Column('tipo', sa.String(length=50), nullable=False))
    op.add_column('paso', sa.Column('api_id', sa.Integer(), nullable=True))
    op.add_column('paso', sa.Column('parametros_json', sa.JSON(), nullable=True))
    op.add_column('paso', sa.Column('extraccion_contexto', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'paso', 'api', ['api_id'], ['id'])
    op.add_column('proyecto', sa.Column('estado', sa.String(length=50), nullable=False))
    op.add_column('proyecto', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('proyecto', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False))
    op.add_column('proyecto', sa.Column('reparticion_id', sa.Integer(), nullable=True))
    op.add_column('proyecto', sa.Column('direccion_id', sa.Integer(), nullable=True))
    op.add_column('proyecto', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proyecto', 'direccion', ['direccion_id'], ['id'])
    op.create_foreign_key(None, 'proyecto', 'reparticion', ['reparticion_id'], ['id'])
    op.create_foreign_key(None, 'proyecto', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proyecto', type_='foreignkey')
    op.drop_constraint(None, 'proyecto', type_='foreignkey')
    op.drop_constraint(None, 'proyecto', type_='foreignkey')
    op.drop_column('proyecto', 'area_id')
    op.drop_column('proyecto', 'direccion_id')
    op.drop_column('proyecto', 'reparticion_id')
    op.drop_column('proyecto', 'fecha_actualizacion')
    op.drop_column('proyecto', 'version')
    op.drop_column('proyecto', 'estado')
    op.drop_constraint(None, 'paso', type_='foreignkey')
    op.drop_column('paso', 'extraccion_contexto')
    op.drop_column('paso', 'parametros_json')
    op.drop_column('paso', 'api_id')
    op.drop_column('paso', 'tipo')
    op.drop_column('paso', 'nombre')
    op.drop_constraint(None, 'modulo', type_='foreignkey')
    op.drop_column('modulo', 'fecha_actualizacion')
    op.drop_column('modulo', 'version')
    op.drop_column('modulo', 'responsable_id')
    op.drop_column('modulo', 'estado')
    op.alter_column('ejecucion', 'resultado_global',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('ejecucion', 'caso_postcondiciones')
    op.drop_column('ejecucion', 'caso_precondiciones')
    op.drop_column('ejecucion', 'caso_objetivo')
    op.drop_column('ejecucion', 'caso_nombre')
    op.drop_column('ejecucion', 'caso_version')
    op.drop_column('ejecucion', 'duracion_ms')
    # ### end Alembic commands ###
