"""add contexto to ejecucion

Revision ID: da6e58363133
Revises: 0c079acd217f
Create Date: 2026-05-14 10:18:16.392043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6e58363133'
down_revision: Union[str, Sequence[str], None] = '0c079acd217f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejecucion_paso', sa.Column('tipo_resultado', sa.Text(), nullable=True))
    op.add_column('ejecucion_paso', sa.Column('request_json', sa.JSON(), nullable=True))
    op.add_column('ejecucion_paso', sa.Column('response_json', sa.JSON(), nullable=True))
    op.add_column('ejecucion_paso', sa.Column('asserts_json', sa.JSON(), nullable=True))
    op.add_column('ejecucion_paso', sa.Column('errores_json', sa.JSON(), nullable=True))
    op.add_column('ejecucion_paso', sa.Column('duracion_ms', sa.Float(), nullable=True))
    op.add_column('ejecucion_paso', sa.Column('parametros_snapshot', sa.JSON(), nullable=True))
    op.add_column('ejecucion_paso', sa.Column('asserts_snapshot', sa.JSON(), nullable=True))
    op.drop_column('ejecucion_paso', 'resultado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejecucion_paso', sa.Column('resultado', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('ejecucion_paso', 'asserts_snapshot')
    op.drop_column('ejecucion_paso', 'parametros_snapshot')
    op.drop_column('ejecucion_paso', 'duracion_ms')
    op.drop_column('ejecucion_paso', 'errores_json')
    op.drop_column('ejecucion_paso', 'asserts_json')
    op.drop_column('ejecucion_paso', 'response_json')
    op.drop_column('ejecucion_paso', 'request_json')
    op.drop_column('ejecucion_paso', 'tipo_resultado')
    # ### end Alembic commands ###
