"""empty base migration

Revision ID: edbfbf831b81
Revises: None
Create Date: 2026-05-05
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbfbf831b81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_permiso_id'), 'permiso', ['id'], unique=False)
    op.create_table('proyecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('objetivo_general', sa.Text(), nullable=True),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_id'), 'proyecto', ['id'], unique=False)
    op.create_table('reparticion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_reparticion_id'), 'reparticion', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('metodo', sa.String(length=10), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('auth_tipo', sa.String(length=20), nullable=False),
    sa.Column('auth_config', sa.Text(), nullable=True),
    sa.Column('headers_por_defecto', sa.Text(), nullable=True),
    sa.Column('body_ejemplo', sa.Text(), nullable=True),
    sa.Column('timeout_segundos', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('modificado_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_api_id'), 'api', ['id'], unique=False)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=False)
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparticion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reparticion_id'], ['reparticion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direccion_id'), 'direccion', ['id'], unique=False)
    op.create_table('modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo_interfaz', sa.String(length=100), nullable=False),
    sa.Column('tipo_gui', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulo_id'), 'modulo', ['id'], unique=False)
    op.create_index(op.f('ix_modulo_proyecto_id'), 'modulo', ['proyecto_id'], unique=False)
    op.create_table('proyecto_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_documento_id'), 'proyecto_documento', ['id'], unique=False)
    op.create_index(op.f('ix_proyecto_documento_proyecto_id'), 'proyecto_documento', ['proyecto_id'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_permiso_id'), 'rol_permiso', ['id'], unique=False)
    op.create_index(op.f('ix_rol_permiso_permiso_id'), 'rol_permiso', ['permiso_id'], unique=False)
    op.create_index(op.f('ix_rol_permiso_rol_id'), 'rol_permiso', ['rol_id'], unique=False)
    op.create_table('usuario_proyecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_proyecto_id'), 'usuario_proyecto', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_proyecto_proyecto_id'), 'usuario_proyecto', ['proyecto_id'], unique=False)
    op.create_index(op.f('ix_usuario_proyecto_usuario_id'), 'usuario_proyecto', ['usuario_id'], unique=False)
    op.create_table('usuario_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_rol_id'), 'usuario_rol', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_rol_rol_id'), 'usuario_rol', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuario_rol_usuario_id'), 'usuario_rol', ['usuario_id'], unique=False)
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_id'), 'area', ['id'], unique=False)
    op.create_table('caso_prueba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('version_actual', sa.Integer(), nullable=False),
    sa.Column('porcentaje_aceptacion', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caso_prueba_id'), 'caso_prueba', ['id'], unique=False)
    op.create_index(op.f('ix_caso_prueba_modulo_id'), 'caso_prueba', ['modulo_id'], unique=False)
    op.create_table('modulo_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulo_documento_id'), 'modulo_documento', ['id'], unique=False)
    op.create_index(op.f('ix_modulo_documento_modulo_id'), 'modulo_documento', ['modulo_id'], unique=False)
    op.create_table('agentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('cuil', sa.String(length=20), nullable=False),
    sa.Column('apellido_nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('reparticion_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_baja', sa.DateTime(), nullable=True),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('modificado_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['reparticion_id'], ['reparticion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuil'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_agentes_id'), 'agentes', ['id'], unique=False)
    op.create_table('caso_prueba_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('nro_version', sa.Integer(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('porcentaje_aceptacion', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['caso_prueba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caso_prueba_version_caso_id'), 'caso_prueba_version', ['caso_id'], unique=False)
    op.create_index(op.f('ix_caso_prueba_version_id'), 'caso_prueba_version', ['id'], unique=False)
    op.create_table('ejecucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_fin', sa.TIMESTAMP(), nullable=True),
    sa.Column('resultado_global', sa.Text(), nullable=True),
    sa.Column('porcentaje_aceptacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['caso_prueba.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecucion_caso_id'), 'ejecucion', ['caso_id'], unique=False)
    op.create_index(op.f('ix_ejecucion_id'), 'ejecucion', ['id'], unique=False)
    op.create_index(op.f('ix_ejecucion_usuario_id'), 'ejecucion', ['usuario_id'], unique=False)
    op.create_table('paso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['caso_id'], ['caso_prueba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paso_api_id'), 'paso', ['api_id'], unique=False)
    op.create_index(op.f('ix_paso_caso_id'), 'paso', ['caso_id'], unique=False)
    op.create_index(op.f('ix_paso_id'), 'paso', ['id'], unique=False)
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=True),
    sa.Column('entidad_tipo', sa.Enum('CASO', 'PASO', 'EJECUCION', 'OBJETO_PARAMETRO', name='entidadtipo_enum'), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecucion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_ejecucion_id'), 'comentario', ['ejecucion_id'], unique=False)
    op.create_index(op.f('ix_comentario_id'), 'comentario', ['id'], unique=False)
    op.create_index(op.f('ix_comentario_usuario_id'), 'comentario', ['usuario_id'], unique=False)
    op.create_table('ejecucion_paso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('paso_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('valor_obtenido', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecucion.id'], ),
    sa.ForeignKeyConstraint(['paso_id'], ['paso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecucion_paso_ejecucion_id'), 'ejecucion_paso', ['ejecucion_id'], unique=False)
    op.create_index(op.f('ix_ejecucion_paso_id'), 'ejecucion_paso', ['id'], unique=False)
    op.create_index(op.f('ix_ejecucion_paso_paso_id'), 'ejecucion_paso', ['paso_id'], unique=False)
    op.create_table('objeto_parametro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paso_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('valor_entrada', sa.Text(), nullable=True),
    sa.Column('valor_esperado', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['paso_id'], ['paso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objeto_parametro_api_id'), 'objeto_parametro', ['api_id'], unique=False)
    op.create_index(op.f('ix_objeto_parametro_id'), 'objeto_parametro', ['id'], unique=False)
    op.create_index(op.f('ix_objeto_parametro_paso_id'), 'objeto_parametro', ['paso_id'], unique=False)
    op.create_table('paso_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paso_id', sa.Integer(), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paso_id'], ['paso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paso_documento_id'), 'paso_documento', ['id'], unique=False)
    op.create_index(op.f('ix_paso_documento_paso_id'), 'paso_documento', ['paso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paso_documento_paso_id'), table_name='paso_documento')
    op.drop_index(op.f('ix_paso_documento_id'), table_name='paso_documento')
    op.drop_table('paso_documento')
    op.drop_index(op.f('ix_objeto_parametro_paso_id'), table_name='objeto_parametro')
    op.drop_index(op.f('ix_objeto_parametro_id'), table_name='objeto_parametro')
    op.drop_index(op.f('ix_objeto_parametro_api_id'), table_name='objeto_parametro')
    op.drop_table('objeto_parametro')
    op.drop_index(op.f('ix_ejecucion_paso_paso_id'), table_name='ejecucion_paso')
    op.drop_index(op.f('ix_ejecucion_paso_id'), table_name='ejecucion_paso')
    op.drop_index(op.f('ix_ejecucion_paso_ejecucion_id'), table_name='ejecucion_paso')
    op.drop_table('ejecucion_paso')
    op.drop_index(op.f('ix_comentario_usuario_id'), table_name='comentario')
    op.drop_index(op.f('ix_comentario_id'), table_name='comentario')
    op.drop_index(op.f('ix_comentario_ejecucion_id'), table_name='comentario')
    op.drop_table('comentario')
    op.drop_index(op.f('ix_paso_id'), table_name='paso')
    op.drop_index(op.f('ix_paso_caso_id'), table_name='paso')
    op.drop_index(op.f('ix_paso_api_id'), table_name='paso')
    op.drop_table('paso')
    op.drop_index(op.f('ix_ejecucion_usuario_id'), table_name='ejecucion')
    op.drop_index(op.f('ix_ejecucion_id'), table_name='ejecucion')
    op.drop_index(op.f('ix_ejecucion_caso_id'), table_name='ejecucion')
    op.drop_table('ejecucion')
    op.drop_index(op.f('ix_caso_prueba_version_id'), table_name='caso_prueba_version')
    op.drop_index(op.f('ix_caso_prueba_version_caso_id'), table_name='caso_prueba_version')
    op.drop_table('caso_prueba_version')
    op.drop_index(op.f('ix_agentes_id'), table_name='agentes')
    op.drop_table('agentes')
    op.drop_index(op.f('ix_modulo_documento_modulo_id'), table_name='modulo_documento')
    op.drop_index(op.f('ix_modulo_documento_id'), table_name='modulo_documento')
    op.drop_table('modulo_documento')
    op.drop_index(op.f('ix_caso_prueba_modulo_id'), table_name='caso_prueba')
    op.drop_index(op.f('ix_caso_prueba_id'), table_name='caso_prueba')
    op.drop_table('caso_prueba')
    op.drop_index(op.f('ix_area_id'), table_name='area')
    op.drop_table('area')
    op.drop_index(op.f('ix_usuario_rol_usuario_id'), table_name='usuario_rol')
    op.drop_index(op.f('ix_usuario_rol_rol_id'), table_name='usuario_rol')
    op.drop_index(op.f('ix_usuario_rol_id'), table_name='usuario_rol')
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_usuario_proyecto_usuario_id'), table_name='usuario_proyecto')
    op.drop_index(op.f('ix_usuario_proyecto_proyecto_id'), table_name='usuario_proyecto')
    op.drop_index(op.f('ix_usuario_proyecto_id'), table_name='usuario_proyecto')
    op.drop_table('usuario_proyecto')
    op.drop_index(op.f('ix_rol_permiso_rol_id'), table_name='rol_permiso')
    op.drop_index(op.f('ix_rol_permiso_permiso_id'), table_name='rol_permiso')
    op.drop_index(op.f('ix_rol_permiso_id'), table_name='rol_permiso')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_proyecto_documento_proyecto_id'), table_name='proyecto_documento')
    op.drop_index(op.f('ix_proyecto_documento_id'), table_name='proyecto_documento')
    op.drop_table('proyecto_documento')
    op.drop_index(op.f('ix_modulo_proyecto_id'), table_name='modulo')
    op.drop_index(op.f('ix_modulo_id'), table_name='modulo')
    op.drop_table('modulo')
    op.drop_index(op.f('ix_direccion_id'), table_name='direccion')
    op.drop_table('direccion')
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_api_id'), table_name='api')
    op.drop_table('api')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_reparticion_id'), table_name='reparticion')
    op.drop_table('reparticion')
    op.drop_index(op.f('ix_proyecto_id'), table_name='proyecto')
    op.drop_table('proyecto')
    op.drop_index(op.f('ix_permiso_id'), table_name='permiso')
    op.drop_table('permiso')
    # ### end Alembic commands ###
